{{- if and .Values.metrics.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sentinel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "sentinel.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  endpoints:
    - port: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.metrics.secure }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
{{- end }}
